// flow-typed signature: 38629781e28256e929f2124d75e87003
// flow-typed version: <<STUB>>/aphrodite_v^2.2.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aphrodite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aphrodite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aphrodite/dist/aphrodite' {
  declare module.exports: any;
}

declare module 'aphrodite/dist/aphrodite.umd' {
  declare module.exports: any;
}

declare module 'aphrodite/dist/aphrodite.umd.min' {
  declare module.exports: any;
}

declare module 'aphrodite/es/chunk-9cf6448a' {
  declare module.exports: any;
}

declare module 'aphrodite/es/index' {
  declare module.exports: any;
}

declare module 'aphrodite/es/no-important' {
  declare module.exports: any;
}

declare module 'aphrodite/examples/runkit' {
  declare module.exports: any;
}

declare module 'aphrodite/examples/server' {
  declare module.exports: any;
}

declare module 'aphrodite/examples/src/examples-ssr' {
  declare module.exports: any;
}

declare module 'aphrodite/examples/src/examples' {
  declare module.exports: any;
}

declare module 'aphrodite/examples/src/StyleTester' {
  declare module.exports: any;
}

declare module 'aphrodite/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'aphrodite/lib/chunk-ff1dea3c' {
  declare module.exports: any;
}

declare module 'aphrodite/lib/index' {
  declare module.exports: any;
}

declare module 'aphrodite/lib/no-important' {
  declare module.exports: any;
}

declare module 'aphrodite/lib/staticPrefixData' {
  declare module.exports: any;
}

declare module 'aphrodite/no-important' {
  declare module.exports: any;
}

declare module 'aphrodite/rollup.config' {
  declare module.exports: any;
}

declare module 'aphrodite/src/exports' {
  declare module.exports: any;
}

declare module 'aphrodite/src/generate' {
  declare module.exports: any;
}

declare module 'aphrodite/src/index' {
  declare module.exports: any;
}

declare module 'aphrodite/src/inject' {
  declare module.exports: any;
}

declare module 'aphrodite/src/no-important' {
  declare module.exports: any;
}

declare module 'aphrodite/src/ordered-elements' {
  declare module.exports: any;
}

declare module 'aphrodite/src/util' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/exports_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/generate_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/index_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/inject_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/no-important_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/ordered-elements_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/testUtils' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/typescript_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tests/util_test' {
  declare module.exports: any;
}

declare module 'aphrodite/tools/generate_prefixer_data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aphrodite/dist/aphrodite.js' {
  declare module.exports: $Exports<'aphrodite/dist/aphrodite'>;
}
declare module 'aphrodite/dist/aphrodite.umd.js' {
  declare module.exports: $Exports<'aphrodite/dist/aphrodite.umd'>;
}
declare module 'aphrodite/dist/aphrodite.umd.min.js' {
  declare module.exports: $Exports<'aphrodite/dist/aphrodite.umd.min'>;
}
declare module 'aphrodite/es/chunk-9cf6448a.js' {
  declare module.exports: $Exports<'aphrodite/es/chunk-9cf6448a'>;
}
declare module 'aphrodite/es/index.js' {
  declare module.exports: $Exports<'aphrodite/es/index'>;
}
declare module 'aphrodite/es/no-important.js' {
  declare module.exports: $Exports<'aphrodite/es/no-important'>;
}
declare module 'aphrodite/examples/runkit.js' {
  declare module.exports: $Exports<'aphrodite/examples/runkit'>;
}
declare module 'aphrodite/examples/server.js' {
  declare module.exports: $Exports<'aphrodite/examples/server'>;
}
declare module 'aphrodite/examples/src/examples-ssr.js' {
  declare module.exports: $Exports<'aphrodite/examples/src/examples-ssr'>;
}
declare module 'aphrodite/examples/src/examples.js' {
  declare module.exports: $Exports<'aphrodite/examples/src/examples'>;
}
declare module 'aphrodite/examples/src/StyleTester.js' {
  declare module.exports: $Exports<'aphrodite/examples/src/StyleTester'>;
}
declare module 'aphrodite/examples/webpack.config.js' {
  declare module.exports: $Exports<'aphrodite/examples/webpack.config'>;
}
declare module 'aphrodite/lib/chunk-ff1dea3c.js' {
  declare module.exports: $Exports<'aphrodite/lib/chunk-ff1dea3c'>;
}
declare module 'aphrodite/lib/index.js' {
  declare module.exports: $Exports<'aphrodite/lib/index'>;
}
declare module 'aphrodite/lib/no-important.js' {
  declare module.exports: $Exports<'aphrodite/lib/no-important'>;
}
declare module 'aphrodite/lib/staticPrefixData.js' {
  declare module.exports: $Exports<'aphrodite/lib/staticPrefixData'>;
}
declare module 'aphrodite/no-important.js' {
  declare module.exports: $Exports<'aphrodite/no-important'>;
}
declare module 'aphrodite/rollup.config.js' {
  declare module.exports: $Exports<'aphrodite/rollup.config'>;
}
declare module 'aphrodite/src/exports.js' {
  declare module.exports: $Exports<'aphrodite/src/exports'>;
}
declare module 'aphrodite/src/generate.js' {
  declare module.exports: $Exports<'aphrodite/src/generate'>;
}
declare module 'aphrodite/src/index.js' {
  declare module.exports: $Exports<'aphrodite/src/index'>;
}
declare module 'aphrodite/src/inject.js' {
  declare module.exports: $Exports<'aphrodite/src/inject'>;
}
declare module 'aphrodite/src/no-important.js' {
  declare module.exports: $Exports<'aphrodite/src/no-important'>;
}
declare module 'aphrodite/src/ordered-elements.js' {
  declare module.exports: $Exports<'aphrodite/src/ordered-elements'>;
}
declare module 'aphrodite/src/util.js' {
  declare module.exports: $Exports<'aphrodite/src/util'>;
}
declare module 'aphrodite/tests/exports_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/exports_test'>;
}
declare module 'aphrodite/tests/generate_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/generate_test'>;
}
declare module 'aphrodite/tests/index_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/index_test'>;
}
declare module 'aphrodite/tests/inject_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/inject_test'>;
}
declare module 'aphrodite/tests/no-important_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/no-important_test'>;
}
declare module 'aphrodite/tests/ordered-elements_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/ordered-elements_test'>;
}
declare module 'aphrodite/tests/testUtils.js' {
  declare module.exports: $Exports<'aphrodite/tests/testUtils'>;
}
declare module 'aphrodite/tests/typescript_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/typescript_test'>;
}
declare module 'aphrodite/tests/util_test.js' {
  declare module.exports: $Exports<'aphrodite/tests/util_test'>;
}
declare module 'aphrodite/tools/generate_prefixer_data.js' {
  declare module.exports: $Exports<'aphrodite/tools/generate_prefixer_data'>;
}
