// flow-typed signature: a1f23b44b5ed5759e82045f5eb5d6e06
// flow-typed version: <<STUB>>/brace_v^0.11.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brace/example/build' {
  declare module.exports: any;
}

declare module 'brace/example/coffee-editor' {
  declare module.exports: any;
}

declare module 'brace/example/css-editor' {
  declare module.exports: any;
}

declare module 'brace/example/javascript-editor' {
  declare module.exports: any;
}

declare module 'brace/example/json-editor' {
  declare module.exports: any;
}

declare module 'brace/example/lua-editor' {
  declare module.exports: any;
}

declare module 'brace/ext/beautify' {
  declare module.exports: any;
}

declare module 'brace/ext/chromevox' {
  declare module.exports: any;
}

declare module 'brace/ext/elastic_tabstops_lite' {
  declare module.exports: any;
}

declare module 'brace/ext/emmet' {
  declare module.exports: any;
}

declare module 'brace/ext/error_marker' {
  declare module.exports: any;
}

declare module 'brace/ext/keybinding_menu' {
  declare module.exports: any;
}

declare module 'brace/ext/language_tools' {
  declare module.exports: any;
}

declare module 'brace/ext/linking' {
  declare module.exports: any;
}

declare module 'brace/ext/modelist' {
  declare module.exports: any;
}

declare module 'brace/ext/old_ie' {
  declare module.exports: any;
}

declare module 'brace/ext/searchbox' {
  declare module.exports: any;
}

declare module 'brace/ext/settings_menu' {
  declare module.exports: any;
}

declare module 'brace/ext/spellcheck' {
  declare module.exports: any;
}

declare module 'brace/ext/split' {
  declare module.exports: any;
}

declare module 'brace/ext/static_highlight' {
  declare module.exports: any;
}

declare module 'brace/ext/statusbar' {
  declare module.exports: any;
}

declare module 'brace/ext/textarea' {
  declare module.exports: any;
}

declare module 'brace/ext/themelist' {
  declare module.exports: any;
}

declare module 'brace/ext/whitespace' {
  declare module.exports: any;
}

declare module 'brace/keybinding/emacs' {
  declare module.exports: any;
}

declare module 'brace/keybinding/vim' {
  declare module.exports: any;
}

declare module 'brace/mode/abap' {
  declare module.exports: any;
}

declare module 'brace/mode/abc' {
  declare module.exports: any;
}

declare module 'brace/mode/actionscript' {
  declare module.exports: any;
}

declare module 'brace/mode/ada' {
  declare module.exports: any;
}

declare module 'brace/mode/apache_conf' {
  declare module.exports: any;
}

declare module 'brace/mode/applescript' {
  declare module.exports: any;
}

declare module 'brace/mode/asciidoc' {
  declare module.exports: any;
}

declare module 'brace/mode/assembly_x86' {
  declare module.exports: any;
}

declare module 'brace/mode/autohotkey' {
  declare module.exports: any;
}

declare module 'brace/mode/batchfile' {
  declare module.exports: any;
}

declare module 'brace/mode/bro' {
  declare module.exports: any;
}

declare module 'brace/mode/c_cpp' {
  declare module.exports: any;
}

declare module 'brace/mode/c9search' {
  declare module.exports: any;
}

declare module 'brace/mode/cirru' {
  declare module.exports: any;
}

declare module 'brace/mode/clojure' {
  declare module.exports: any;
}

declare module 'brace/mode/cobol' {
  declare module.exports: any;
}

declare module 'brace/mode/coffee' {
  declare module.exports: any;
}

declare module 'brace/mode/coldfusion' {
  declare module.exports: any;
}

declare module 'brace/mode/csharp' {
  declare module.exports: any;
}

declare module 'brace/mode/csound_document' {
  declare module.exports: any;
}

declare module 'brace/mode/csound_orchestra' {
  declare module.exports: any;
}

declare module 'brace/mode/csound_score' {
  declare module.exports: any;
}

declare module 'brace/mode/css' {
  declare module.exports: any;
}

declare module 'brace/mode/curly' {
  declare module.exports: any;
}

declare module 'brace/mode/d' {
  declare module.exports: any;
}

declare module 'brace/mode/dart' {
  declare module.exports: any;
}

declare module 'brace/mode/diff' {
  declare module.exports: any;
}

declare module 'brace/mode/django' {
  declare module.exports: any;
}

declare module 'brace/mode/dockerfile' {
  declare module.exports: any;
}

declare module 'brace/mode/dot' {
  declare module.exports: any;
}

declare module 'brace/mode/drools' {
  declare module.exports: any;
}

declare module 'brace/mode/eiffel' {
  declare module.exports: any;
}

declare module 'brace/mode/ejs' {
  declare module.exports: any;
}

declare module 'brace/mode/elixir' {
  declare module.exports: any;
}

declare module 'brace/mode/elm' {
  declare module.exports: any;
}

declare module 'brace/mode/erlang' {
  declare module.exports: any;
}

declare module 'brace/mode/forth' {
  declare module.exports: any;
}

declare module 'brace/mode/fortran' {
  declare module.exports: any;
}

declare module 'brace/mode/ftl' {
  declare module.exports: any;
}

declare module 'brace/mode/gcode' {
  declare module.exports: any;
}

declare module 'brace/mode/gherkin' {
  declare module.exports: any;
}

declare module 'brace/mode/gitignore' {
  declare module.exports: any;
}

declare module 'brace/mode/glsl' {
  declare module.exports: any;
}

declare module 'brace/mode/gobstones' {
  declare module.exports: any;
}

declare module 'brace/mode/golang' {
  declare module.exports: any;
}

declare module 'brace/mode/graphqlschema' {
  declare module.exports: any;
}

declare module 'brace/mode/groovy' {
  declare module.exports: any;
}

declare module 'brace/mode/haml' {
  declare module.exports: any;
}

declare module 'brace/mode/handlebars' {
  declare module.exports: any;
}

declare module 'brace/mode/haskell_cabal' {
  declare module.exports: any;
}

declare module 'brace/mode/haskell' {
  declare module.exports: any;
}

declare module 'brace/mode/haxe' {
  declare module.exports: any;
}

declare module 'brace/mode/hjson' {
  declare module.exports: any;
}

declare module 'brace/mode/html_elixir' {
  declare module.exports: any;
}

declare module 'brace/mode/html_ruby' {
  declare module.exports: any;
}

declare module 'brace/mode/html' {
  declare module.exports: any;
}

declare module 'brace/mode/ini' {
  declare module.exports: any;
}

declare module 'brace/mode/io' {
  declare module.exports: any;
}

declare module 'brace/mode/jack' {
  declare module.exports: any;
}

declare module 'brace/mode/jade' {
  declare module.exports: any;
}

declare module 'brace/mode/java' {
  declare module.exports: any;
}

declare module 'brace/mode/javascript' {
  declare module.exports: any;
}

declare module 'brace/mode/json' {
  declare module.exports: any;
}

declare module 'brace/mode/jsoniq' {
  declare module.exports: any;
}

declare module 'brace/mode/jsp' {
  declare module.exports: any;
}

declare module 'brace/mode/jssm' {
  declare module.exports: any;
}

declare module 'brace/mode/jsx' {
  declare module.exports: any;
}

declare module 'brace/mode/julia' {
  declare module.exports: any;
}

declare module 'brace/mode/kotlin' {
  declare module.exports: any;
}

declare module 'brace/mode/latex' {
  declare module.exports: any;
}

declare module 'brace/mode/lean' {
  declare module.exports: any;
}

declare module 'brace/mode/less' {
  declare module.exports: any;
}

declare module 'brace/mode/liquid' {
  declare module.exports: any;
}

declare module 'brace/mode/lisp' {
  declare module.exports: any;
}

declare module 'brace/mode/live_script' {
  declare module.exports: any;
}

declare module 'brace/mode/livescript' {
  declare module.exports: any;
}

declare module 'brace/mode/logiql' {
  declare module.exports: any;
}

declare module 'brace/mode/lsl' {
  declare module.exports: any;
}

declare module 'brace/mode/lua' {
  declare module.exports: any;
}

declare module 'brace/mode/luapage' {
  declare module.exports: any;
}

declare module 'brace/mode/lucene' {
  declare module.exports: any;
}

declare module 'brace/mode/makefile' {
  declare module.exports: any;
}

declare module 'brace/mode/markdown' {
  declare module.exports: any;
}

declare module 'brace/mode/mask' {
  declare module.exports: any;
}

declare module 'brace/mode/matlab' {
  declare module.exports: any;
}

declare module 'brace/mode/mavens_mate_log' {
  declare module.exports: any;
}

declare module 'brace/mode/maze' {
  declare module.exports: any;
}

declare module 'brace/mode/mel' {
  declare module.exports: any;
}

declare module 'brace/mode/mips_assembler' {
  declare module.exports: any;
}

declare module 'brace/mode/mipsassembler' {
  declare module.exports: any;
}

declare module 'brace/mode/mushcode' {
  declare module.exports: any;
}

declare module 'brace/mode/mysql' {
  declare module.exports: any;
}

declare module 'brace/mode/nix' {
  declare module.exports: any;
}

declare module 'brace/mode/nsis' {
  declare module.exports: any;
}

declare module 'brace/mode/objectivec' {
  declare module.exports: any;
}

declare module 'brace/mode/ocaml' {
  declare module.exports: any;
}

declare module 'brace/mode/pascal' {
  declare module.exports: any;
}

declare module 'brace/mode/perl' {
  declare module.exports: any;
}

declare module 'brace/mode/pgsql' {
  declare module.exports: any;
}

declare module 'brace/mode/php' {
  declare module.exports: any;
}

declare module 'brace/mode/pig' {
  declare module.exports: any;
}

declare module 'brace/mode/plain_text' {
  declare module.exports: any;
}

declare module 'brace/mode/powershell' {
  declare module.exports: any;
}

declare module 'brace/mode/praat' {
  declare module.exports: any;
}

declare module 'brace/mode/prolog' {
  declare module.exports: any;
}

declare module 'brace/mode/properties' {
  declare module.exports: any;
}

declare module 'brace/mode/protobuf' {
  declare module.exports: any;
}

declare module 'brace/mode/python' {
  declare module.exports: any;
}

declare module 'brace/mode/r' {
  declare module.exports: any;
}

declare module 'brace/mode/razor' {
  declare module.exports: any;
}

declare module 'brace/mode/rdoc' {
  declare module.exports: any;
}

declare module 'brace/mode/red' {
  declare module.exports: any;
}

declare module 'brace/mode/rhtml' {
  declare module.exports: any;
}

declare module 'brace/mode/rst' {
  declare module.exports: any;
}

declare module 'brace/mode/ruby' {
  declare module.exports: any;
}

declare module 'brace/mode/rust' {
  declare module.exports: any;
}

declare module 'brace/mode/sass' {
  declare module.exports: any;
}

declare module 'brace/mode/scad' {
  declare module.exports: any;
}

declare module 'brace/mode/scala' {
  declare module.exports: any;
}

declare module 'brace/mode/scheme' {
  declare module.exports: any;
}

declare module 'brace/mode/scss' {
  declare module.exports: any;
}

declare module 'brace/mode/sh' {
  declare module.exports: any;
}

declare module 'brace/mode/sjs' {
  declare module.exports: any;
}

declare module 'brace/mode/smarty' {
  declare module.exports: any;
}

declare module 'brace/mode/snippets' {
  declare module.exports: any;
}

declare module 'brace/mode/soy_template' {
  declare module.exports: any;
}

declare module 'brace/mode/space' {
  declare module.exports: any;
}

declare module 'brace/mode/sparql' {
  declare module.exports: any;
}

declare module 'brace/mode/sql' {
  declare module.exports: any;
}

declare module 'brace/mode/sqlserver' {
  declare module.exports: any;
}

declare module 'brace/mode/stylus' {
  declare module.exports: any;
}

declare module 'brace/mode/svg' {
  declare module.exports: any;
}

declare module 'brace/mode/swift' {
  declare module.exports: any;
}

declare module 'brace/mode/swig' {
  declare module.exports: any;
}

declare module 'brace/mode/tcl' {
  declare module.exports: any;
}

declare module 'brace/mode/tex' {
  declare module.exports: any;
}

declare module 'brace/mode/text' {
  declare module.exports: any;
}

declare module 'brace/mode/textile' {
  declare module.exports: any;
}

declare module 'brace/mode/toml' {
  declare module.exports: any;
}

declare module 'brace/mode/tsx' {
  declare module.exports: any;
}

declare module 'brace/mode/turtle' {
  declare module.exports: any;
}

declare module 'brace/mode/twig' {
  declare module.exports: any;
}

declare module 'brace/mode/typescript' {
  declare module.exports: any;
}

declare module 'brace/mode/vala' {
  declare module.exports: any;
}

declare module 'brace/mode/vbscript' {
  declare module.exports: any;
}

declare module 'brace/mode/velocity' {
  declare module.exports: any;
}

declare module 'brace/mode/verilog' {
  declare module.exports: any;
}

declare module 'brace/mode/vhdl' {
  declare module.exports: any;
}

declare module 'brace/mode/wollok' {
  declare module.exports: any;
}

declare module 'brace/mode/xml' {
  declare module.exports: any;
}

declare module 'brace/mode/xquery' {
  declare module.exports: any;
}

declare module 'brace/mode/yaml' {
  declare module.exports: any;
}

declare module 'brace/snippets/abap' {
  declare module.exports: any;
}

declare module 'brace/snippets/abc' {
  declare module.exports: any;
}

declare module 'brace/snippets/actionscript' {
  declare module.exports: any;
}

declare module 'brace/snippets/ada' {
  declare module.exports: any;
}

declare module 'brace/snippets/apache_conf' {
  declare module.exports: any;
}

declare module 'brace/snippets/applescript' {
  declare module.exports: any;
}

declare module 'brace/snippets/asciidoc' {
  declare module.exports: any;
}

declare module 'brace/snippets/assembly_x86' {
  declare module.exports: any;
}

declare module 'brace/snippets/autohotkey' {
  declare module.exports: any;
}

declare module 'brace/snippets/batchfile' {
  declare module.exports: any;
}

declare module 'brace/snippets/bro' {
  declare module.exports: any;
}

declare module 'brace/snippets/c_cpp' {
  declare module.exports: any;
}

declare module 'brace/snippets/c9search' {
  declare module.exports: any;
}

declare module 'brace/snippets/cirru' {
  declare module.exports: any;
}

declare module 'brace/snippets/clojure' {
  declare module.exports: any;
}

declare module 'brace/snippets/cobol' {
  declare module.exports: any;
}

declare module 'brace/snippets/coffee' {
  declare module.exports: any;
}

declare module 'brace/snippets/coldfusion' {
  declare module.exports: any;
}

declare module 'brace/snippets/csharp' {
  declare module.exports: any;
}

declare module 'brace/snippets/csound_document' {
  declare module.exports: any;
}

declare module 'brace/snippets/csound_orchestra' {
  declare module.exports: any;
}

declare module 'brace/snippets/csound_score' {
  declare module.exports: any;
}

declare module 'brace/snippets/css' {
  declare module.exports: any;
}

declare module 'brace/snippets/curly' {
  declare module.exports: any;
}

declare module 'brace/snippets/d' {
  declare module.exports: any;
}

declare module 'brace/snippets/dart' {
  declare module.exports: any;
}

declare module 'brace/snippets/diff' {
  declare module.exports: any;
}

declare module 'brace/snippets/django' {
  declare module.exports: any;
}

declare module 'brace/snippets/dockerfile' {
  declare module.exports: any;
}

declare module 'brace/snippets/dot' {
  declare module.exports: any;
}

declare module 'brace/snippets/drools' {
  declare module.exports: any;
}

declare module 'brace/snippets/eiffel' {
  declare module.exports: any;
}

declare module 'brace/snippets/ejs' {
  declare module.exports: any;
}

declare module 'brace/snippets/elixir' {
  declare module.exports: any;
}

declare module 'brace/snippets/elm' {
  declare module.exports: any;
}

declare module 'brace/snippets/erlang' {
  declare module.exports: any;
}

declare module 'brace/snippets/forth' {
  declare module.exports: any;
}

declare module 'brace/snippets/fortran' {
  declare module.exports: any;
}

declare module 'brace/snippets/ftl' {
  declare module.exports: any;
}

declare module 'brace/snippets/gcode' {
  declare module.exports: any;
}

declare module 'brace/snippets/gherkin' {
  declare module.exports: any;
}

declare module 'brace/snippets/gitignore' {
  declare module.exports: any;
}

declare module 'brace/snippets/glsl' {
  declare module.exports: any;
}

declare module 'brace/snippets/gobstones' {
  declare module.exports: any;
}

declare module 'brace/snippets/golang' {
  declare module.exports: any;
}

declare module 'brace/snippets/graphqlschema' {
  declare module.exports: any;
}

declare module 'brace/snippets/groovy' {
  declare module.exports: any;
}

declare module 'brace/snippets/haml' {
  declare module.exports: any;
}

declare module 'brace/snippets/handlebars' {
  declare module.exports: any;
}

declare module 'brace/snippets/haskell_cabal' {
  declare module.exports: any;
}

declare module 'brace/snippets/haskell' {
  declare module.exports: any;
}

declare module 'brace/snippets/haxe' {
  declare module.exports: any;
}

declare module 'brace/snippets/hjson' {
  declare module.exports: any;
}

declare module 'brace/snippets/html_elixir' {
  declare module.exports: any;
}

declare module 'brace/snippets/html_ruby' {
  declare module.exports: any;
}

declare module 'brace/snippets/html' {
  declare module.exports: any;
}

declare module 'brace/snippets/ini' {
  declare module.exports: any;
}

declare module 'brace/snippets/io' {
  declare module.exports: any;
}

declare module 'brace/snippets/jack' {
  declare module.exports: any;
}

declare module 'brace/snippets/jade' {
  declare module.exports: any;
}

declare module 'brace/snippets/java' {
  declare module.exports: any;
}

declare module 'brace/snippets/javascript' {
  declare module.exports: any;
}

declare module 'brace/snippets/json' {
  declare module.exports: any;
}

declare module 'brace/snippets/jsoniq' {
  declare module.exports: any;
}

declare module 'brace/snippets/jsp' {
  declare module.exports: any;
}

declare module 'brace/snippets/jssm' {
  declare module.exports: any;
}

declare module 'brace/snippets/jsx' {
  declare module.exports: any;
}

declare module 'brace/snippets/julia' {
  declare module.exports: any;
}

declare module 'brace/snippets/kotlin' {
  declare module.exports: any;
}

declare module 'brace/snippets/latex' {
  declare module.exports: any;
}

declare module 'brace/snippets/lean' {
  declare module.exports: any;
}

declare module 'brace/snippets/less' {
  declare module.exports: any;
}

declare module 'brace/snippets/liquid' {
  declare module.exports: any;
}

declare module 'brace/snippets/lisp' {
  declare module.exports: any;
}

declare module 'brace/snippets/live_script' {
  declare module.exports: any;
}

declare module 'brace/snippets/livescript' {
  declare module.exports: any;
}

declare module 'brace/snippets/logiql' {
  declare module.exports: any;
}

declare module 'brace/snippets/lsl' {
  declare module.exports: any;
}

declare module 'brace/snippets/lua' {
  declare module.exports: any;
}

declare module 'brace/snippets/luapage' {
  declare module.exports: any;
}

declare module 'brace/snippets/lucene' {
  declare module.exports: any;
}

declare module 'brace/snippets/makefile' {
  declare module.exports: any;
}

declare module 'brace/snippets/markdown' {
  declare module.exports: any;
}

declare module 'brace/snippets/mask' {
  declare module.exports: any;
}

declare module 'brace/snippets/matlab' {
  declare module.exports: any;
}

declare module 'brace/snippets/maze' {
  declare module.exports: any;
}

declare module 'brace/snippets/mel' {
  declare module.exports: any;
}

declare module 'brace/snippets/mips_assembler' {
  declare module.exports: any;
}

declare module 'brace/snippets/mipsassembler' {
  declare module.exports: any;
}

declare module 'brace/snippets/mushcode' {
  declare module.exports: any;
}

declare module 'brace/snippets/mysql' {
  declare module.exports: any;
}

declare module 'brace/snippets/nix' {
  declare module.exports: any;
}

declare module 'brace/snippets/nsis' {
  declare module.exports: any;
}

declare module 'brace/snippets/objectivec' {
  declare module.exports: any;
}

declare module 'brace/snippets/ocaml' {
  declare module.exports: any;
}

declare module 'brace/snippets/pascal' {
  declare module.exports: any;
}

declare module 'brace/snippets/perl' {
  declare module.exports: any;
}

declare module 'brace/snippets/pgsql' {
  declare module.exports: any;
}

declare module 'brace/snippets/php' {
  declare module.exports: any;
}

declare module 'brace/snippets/pig' {
  declare module.exports: any;
}

declare module 'brace/snippets/plain_text' {
  declare module.exports: any;
}

declare module 'brace/snippets/powershell' {
  declare module.exports: any;
}

declare module 'brace/snippets/praat' {
  declare module.exports: any;
}

declare module 'brace/snippets/prolog' {
  declare module.exports: any;
}

declare module 'brace/snippets/properties' {
  declare module.exports: any;
}

declare module 'brace/snippets/protobuf' {
  declare module.exports: any;
}

declare module 'brace/snippets/python' {
  declare module.exports: any;
}

declare module 'brace/snippets/r' {
  declare module.exports: any;
}

declare module 'brace/snippets/razor' {
  declare module.exports: any;
}

declare module 'brace/snippets/rdoc' {
  declare module.exports: any;
}

declare module 'brace/snippets/red' {
  declare module.exports: any;
}

declare module 'brace/snippets/rhtml' {
  declare module.exports: any;
}

declare module 'brace/snippets/rst' {
  declare module.exports: any;
}

declare module 'brace/snippets/ruby' {
  declare module.exports: any;
}

declare module 'brace/snippets/rust' {
  declare module.exports: any;
}

declare module 'brace/snippets/sass' {
  declare module.exports: any;
}

declare module 'brace/snippets/scad' {
  declare module.exports: any;
}

declare module 'brace/snippets/scala' {
  declare module.exports: any;
}

declare module 'brace/snippets/scheme' {
  declare module.exports: any;
}

declare module 'brace/snippets/scss' {
  declare module.exports: any;
}

declare module 'brace/snippets/sh' {
  declare module.exports: any;
}

declare module 'brace/snippets/sjs' {
  declare module.exports: any;
}

declare module 'brace/snippets/smarty' {
  declare module.exports: any;
}

declare module 'brace/snippets/snippets' {
  declare module.exports: any;
}

declare module 'brace/snippets/soy_template' {
  declare module.exports: any;
}

declare module 'brace/snippets/space' {
  declare module.exports: any;
}

declare module 'brace/snippets/sparql' {
  declare module.exports: any;
}

declare module 'brace/snippets/sql' {
  declare module.exports: any;
}

declare module 'brace/snippets/sqlserver' {
  declare module.exports: any;
}

declare module 'brace/snippets/stylus' {
  declare module.exports: any;
}

declare module 'brace/snippets/svg' {
  declare module.exports: any;
}

declare module 'brace/snippets/swift' {
  declare module.exports: any;
}

declare module 'brace/snippets/swig' {
  declare module.exports: any;
}

declare module 'brace/snippets/tcl' {
  declare module.exports: any;
}

declare module 'brace/snippets/tex' {
  declare module.exports: any;
}

declare module 'brace/snippets/text' {
  declare module.exports: any;
}

declare module 'brace/snippets/textile' {
  declare module.exports: any;
}

declare module 'brace/snippets/toml' {
  declare module.exports: any;
}

declare module 'brace/snippets/tsx' {
  declare module.exports: any;
}

declare module 'brace/snippets/turtle' {
  declare module.exports: any;
}

declare module 'brace/snippets/twig' {
  declare module.exports: any;
}

declare module 'brace/snippets/typescript' {
  declare module.exports: any;
}

declare module 'brace/snippets/vala' {
  declare module.exports: any;
}

declare module 'brace/snippets/vbscript' {
  declare module.exports: any;
}

declare module 'brace/snippets/velocity' {
  declare module.exports: any;
}

declare module 'brace/snippets/verilog' {
  declare module.exports: any;
}

declare module 'brace/snippets/vhdl' {
  declare module.exports: any;
}

declare module 'brace/snippets/wollok' {
  declare module.exports: any;
}

declare module 'brace/snippets/xml' {
  declare module.exports: any;
}

declare module 'brace/snippets/xquery' {
  declare module.exports: any;
}

declare module 'brace/snippets/yaml' {
  declare module.exports: any;
}

declare module 'brace/test/error-annotations' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/coffee-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/javascript-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/json-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/lua-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/xml-editor' {
  declare module.exports: any;
}

declare module 'brace/test/stringified/style' {
  declare module.exports: any;
}

declare module 'brace/theme/ambiance' {
  declare module.exports: any;
}

declare module 'brace/theme/chaos' {
  declare module.exports: any;
}

declare module 'brace/theme/chrome' {
  declare module.exports: any;
}

declare module 'brace/theme/clouds_midnight' {
  declare module.exports: any;
}

declare module 'brace/theme/clouds' {
  declare module.exports: any;
}

declare module 'brace/theme/cobalt' {
  declare module.exports: any;
}

declare module 'brace/theme/crimson_editor' {
  declare module.exports: any;
}

declare module 'brace/theme/dawn' {
  declare module.exports: any;
}

declare module 'brace/theme/dracula' {
  declare module.exports: any;
}

declare module 'brace/theme/dreamweaver' {
  declare module.exports: any;
}

declare module 'brace/theme/eclipse' {
  declare module.exports: any;
}

declare module 'brace/theme/github' {
  declare module.exports: any;
}

declare module 'brace/theme/gob' {
  declare module.exports: any;
}

declare module 'brace/theme/gruvbox' {
  declare module.exports: any;
}

declare module 'brace/theme/idle_fingers' {
  declare module.exports: any;
}

declare module 'brace/theme/iplastic' {
  declare module.exports: any;
}

declare module 'brace/theme/katzenmilch' {
  declare module.exports: any;
}

declare module 'brace/theme/kr_theme' {
  declare module.exports: any;
}

declare module 'brace/theme/kuroir' {
  declare module.exports: any;
}

declare module 'brace/theme/merbivore_soft' {
  declare module.exports: any;
}

declare module 'brace/theme/merbivore' {
  declare module.exports: any;
}

declare module 'brace/theme/mono_industrial' {
  declare module.exports: any;
}

declare module 'brace/theme/monokai' {
  declare module.exports: any;
}

declare module 'brace/theme/pastel_on_dark' {
  declare module.exports: any;
}

declare module 'brace/theme/solarized_dark' {
  declare module.exports: any;
}

declare module 'brace/theme/solarized_light' {
  declare module.exports: any;
}

declare module 'brace/theme/sqlserver' {
  declare module.exports: any;
}

declare module 'brace/theme/terminal' {
  declare module.exports: any;
}

declare module 'brace/theme/textmate' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night_blue' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night_bright' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night_eighties' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow' {
  declare module.exports: any;
}

declare module 'brace/theme/twilight' {
  declare module.exports: any;
}

declare module 'brace/theme/vibrant_ink' {
  declare module.exports: any;
}

declare module 'brace/theme/xcode' {
  declare module.exports: any;
}

declare module 'brace/worker/coffee' {
  declare module.exports: any;
}

declare module 'brace/worker/css' {
  declare module.exports: any;
}

declare module 'brace/worker/html' {
  declare module.exports: any;
}

declare module 'brace/worker/javascript' {
  declare module.exports: any;
}

declare module 'brace/worker/json' {
  declare module.exports: any;
}

declare module 'brace/worker/lua' {
  declare module.exports: any;
}

declare module 'brace/worker/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brace/example/build.js' {
  declare module.exports: $Exports<'brace/example/build'>;
}
declare module 'brace/example/coffee-editor.js' {
  declare module.exports: $Exports<'brace/example/coffee-editor'>;
}
declare module 'brace/example/css-editor.js' {
  declare module.exports: $Exports<'brace/example/css-editor'>;
}
declare module 'brace/example/javascript-editor.js' {
  declare module.exports: $Exports<'brace/example/javascript-editor'>;
}
declare module 'brace/example/json-editor.js' {
  declare module.exports: $Exports<'brace/example/json-editor'>;
}
declare module 'brace/example/lua-editor.js' {
  declare module.exports: $Exports<'brace/example/lua-editor'>;
}
declare module 'brace/ext/beautify.js' {
  declare module.exports: $Exports<'brace/ext/beautify'>;
}
declare module 'brace/ext/chromevox.js' {
  declare module.exports: $Exports<'brace/ext/chromevox'>;
}
declare module 'brace/ext/elastic_tabstops_lite.js' {
  declare module.exports: $Exports<'brace/ext/elastic_tabstops_lite'>;
}
declare module 'brace/ext/emmet.js' {
  declare module.exports: $Exports<'brace/ext/emmet'>;
}
declare module 'brace/ext/error_marker.js' {
  declare module.exports: $Exports<'brace/ext/error_marker'>;
}
declare module 'brace/ext/keybinding_menu.js' {
  declare module.exports: $Exports<'brace/ext/keybinding_menu'>;
}
declare module 'brace/ext/language_tools.js' {
  declare module.exports: $Exports<'brace/ext/language_tools'>;
}
declare module 'brace/ext/linking.js' {
  declare module.exports: $Exports<'brace/ext/linking'>;
}
declare module 'brace/ext/modelist.js' {
  declare module.exports: $Exports<'brace/ext/modelist'>;
}
declare module 'brace/ext/old_ie.js' {
  declare module.exports: $Exports<'brace/ext/old_ie'>;
}
declare module 'brace/ext/searchbox.js' {
  declare module.exports: $Exports<'brace/ext/searchbox'>;
}
declare module 'brace/ext/settings_menu.js' {
  declare module.exports: $Exports<'brace/ext/settings_menu'>;
}
declare module 'brace/ext/spellcheck.js' {
  declare module.exports: $Exports<'brace/ext/spellcheck'>;
}
declare module 'brace/ext/split.js' {
  declare module.exports: $Exports<'brace/ext/split'>;
}
declare module 'brace/ext/static_highlight.js' {
  declare module.exports: $Exports<'brace/ext/static_highlight'>;
}
declare module 'brace/ext/statusbar.js' {
  declare module.exports: $Exports<'brace/ext/statusbar'>;
}
declare module 'brace/ext/textarea.js' {
  declare module.exports: $Exports<'brace/ext/textarea'>;
}
declare module 'brace/ext/themelist.js' {
  declare module.exports: $Exports<'brace/ext/themelist'>;
}
declare module 'brace/ext/whitespace.js' {
  declare module.exports: $Exports<'brace/ext/whitespace'>;
}
declare module 'brace/index' {
  declare module.exports: $Exports<'brace'>;
}
declare module 'brace/index.js' {
  declare module.exports: $Exports<'brace'>;
}
declare module 'brace/keybinding/emacs.js' {
  declare module.exports: $Exports<'brace/keybinding/emacs'>;
}
declare module 'brace/keybinding/vim.js' {
  declare module.exports: $Exports<'brace/keybinding/vim'>;
}
declare module 'brace/mode/abap.js' {
  declare module.exports: $Exports<'brace/mode/abap'>;
}
declare module 'brace/mode/abc.js' {
  declare module.exports: $Exports<'brace/mode/abc'>;
}
declare module 'brace/mode/actionscript.js' {
  declare module.exports: $Exports<'brace/mode/actionscript'>;
}
declare module 'brace/mode/ada.js' {
  declare module.exports: $Exports<'brace/mode/ada'>;
}
declare module 'brace/mode/apache_conf.js' {
  declare module.exports: $Exports<'brace/mode/apache_conf'>;
}
declare module 'brace/mode/applescript.js' {
  declare module.exports: $Exports<'brace/mode/applescript'>;
}
declare module 'brace/mode/asciidoc.js' {
  declare module.exports: $Exports<'brace/mode/asciidoc'>;
}
declare module 'brace/mode/assembly_x86.js' {
  declare module.exports: $Exports<'brace/mode/assembly_x86'>;
}
declare module 'brace/mode/autohotkey.js' {
  declare module.exports: $Exports<'brace/mode/autohotkey'>;
}
declare module 'brace/mode/batchfile.js' {
  declare module.exports: $Exports<'brace/mode/batchfile'>;
}
declare module 'brace/mode/bro.js' {
  declare module.exports: $Exports<'brace/mode/bro'>;
}
declare module 'brace/mode/c_cpp.js' {
  declare module.exports: $Exports<'brace/mode/c_cpp'>;
}
declare module 'brace/mode/c9search.js' {
  declare module.exports: $Exports<'brace/mode/c9search'>;
}
declare module 'brace/mode/cirru.js' {
  declare module.exports: $Exports<'brace/mode/cirru'>;
}
declare module 'brace/mode/clojure.js' {
  declare module.exports: $Exports<'brace/mode/clojure'>;
}
declare module 'brace/mode/cobol.js' {
  declare module.exports: $Exports<'brace/mode/cobol'>;
}
declare module 'brace/mode/coffee.js' {
  declare module.exports: $Exports<'brace/mode/coffee'>;
}
declare module 'brace/mode/coldfusion.js' {
  declare module.exports: $Exports<'brace/mode/coldfusion'>;
}
declare module 'brace/mode/csharp.js' {
  declare module.exports: $Exports<'brace/mode/csharp'>;
}
declare module 'brace/mode/csound_document.js' {
  declare module.exports: $Exports<'brace/mode/csound_document'>;
}
declare module 'brace/mode/csound_orchestra.js' {
  declare module.exports: $Exports<'brace/mode/csound_orchestra'>;
}
declare module 'brace/mode/csound_score.js' {
  declare module.exports: $Exports<'brace/mode/csound_score'>;
}
declare module 'brace/mode/css.js' {
  declare module.exports: $Exports<'brace/mode/css'>;
}
declare module 'brace/mode/curly.js' {
  declare module.exports: $Exports<'brace/mode/curly'>;
}
declare module 'brace/mode/d.js' {
  declare module.exports: $Exports<'brace/mode/d'>;
}
declare module 'brace/mode/dart.js' {
  declare module.exports: $Exports<'brace/mode/dart'>;
}
declare module 'brace/mode/diff.js' {
  declare module.exports: $Exports<'brace/mode/diff'>;
}
declare module 'brace/mode/django.js' {
  declare module.exports: $Exports<'brace/mode/django'>;
}
declare module 'brace/mode/dockerfile.js' {
  declare module.exports: $Exports<'brace/mode/dockerfile'>;
}
declare module 'brace/mode/dot.js' {
  declare module.exports: $Exports<'brace/mode/dot'>;
}
declare module 'brace/mode/drools.js' {
  declare module.exports: $Exports<'brace/mode/drools'>;
}
declare module 'brace/mode/eiffel.js' {
  declare module.exports: $Exports<'brace/mode/eiffel'>;
}
declare module 'brace/mode/ejs.js' {
  declare module.exports: $Exports<'brace/mode/ejs'>;
}
declare module 'brace/mode/elixir.js' {
  declare module.exports: $Exports<'brace/mode/elixir'>;
}
declare module 'brace/mode/elm.js' {
  declare module.exports: $Exports<'brace/mode/elm'>;
}
declare module 'brace/mode/erlang.js' {
  declare module.exports: $Exports<'brace/mode/erlang'>;
}
declare module 'brace/mode/forth.js' {
  declare module.exports: $Exports<'brace/mode/forth'>;
}
declare module 'brace/mode/fortran.js' {
  declare module.exports: $Exports<'brace/mode/fortran'>;
}
declare module 'brace/mode/ftl.js' {
  declare module.exports: $Exports<'brace/mode/ftl'>;
}
declare module 'brace/mode/gcode.js' {
  declare module.exports: $Exports<'brace/mode/gcode'>;
}
declare module 'brace/mode/gherkin.js' {
  declare module.exports: $Exports<'brace/mode/gherkin'>;
}
declare module 'brace/mode/gitignore.js' {
  declare module.exports: $Exports<'brace/mode/gitignore'>;
}
declare module 'brace/mode/glsl.js' {
  declare module.exports: $Exports<'brace/mode/glsl'>;
}
declare module 'brace/mode/gobstones.js' {
  declare module.exports: $Exports<'brace/mode/gobstones'>;
}
declare module 'brace/mode/golang.js' {
  declare module.exports: $Exports<'brace/mode/golang'>;
}
declare module 'brace/mode/graphqlschema.js' {
  declare module.exports: $Exports<'brace/mode/graphqlschema'>;
}
declare module 'brace/mode/groovy.js' {
  declare module.exports: $Exports<'brace/mode/groovy'>;
}
declare module 'brace/mode/haml.js' {
  declare module.exports: $Exports<'brace/mode/haml'>;
}
declare module 'brace/mode/handlebars.js' {
  declare module.exports: $Exports<'brace/mode/handlebars'>;
}
declare module 'brace/mode/haskell_cabal.js' {
  declare module.exports: $Exports<'brace/mode/haskell_cabal'>;
}
declare module 'brace/mode/haskell.js' {
  declare module.exports: $Exports<'brace/mode/haskell'>;
}
declare module 'brace/mode/haxe.js' {
  declare module.exports: $Exports<'brace/mode/haxe'>;
}
declare module 'brace/mode/hjson.js' {
  declare module.exports: $Exports<'brace/mode/hjson'>;
}
declare module 'brace/mode/html_elixir.js' {
  declare module.exports: $Exports<'brace/mode/html_elixir'>;
}
declare module 'brace/mode/html_ruby.js' {
  declare module.exports: $Exports<'brace/mode/html_ruby'>;
}
declare module 'brace/mode/html.js' {
  declare module.exports: $Exports<'brace/mode/html'>;
}
declare module 'brace/mode/ini.js' {
  declare module.exports: $Exports<'brace/mode/ini'>;
}
declare module 'brace/mode/io.js' {
  declare module.exports: $Exports<'brace/mode/io'>;
}
declare module 'brace/mode/jack.js' {
  declare module.exports: $Exports<'brace/mode/jack'>;
}
declare module 'brace/mode/jade.js' {
  declare module.exports: $Exports<'brace/mode/jade'>;
}
declare module 'brace/mode/java.js' {
  declare module.exports: $Exports<'brace/mode/java'>;
}
declare module 'brace/mode/javascript.js' {
  declare module.exports: $Exports<'brace/mode/javascript'>;
}
declare module 'brace/mode/json.js' {
  declare module.exports: $Exports<'brace/mode/json'>;
}
declare module 'brace/mode/jsoniq.js' {
  declare module.exports: $Exports<'brace/mode/jsoniq'>;
}
declare module 'brace/mode/jsp.js' {
  declare module.exports: $Exports<'brace/mode/jsp'>;
}
declare module 'brace/mode/jssm.js' {
  declare module.exports: $Exports<'brace/mode/jssm'>;
}
declare module 'brace/mode/jsx.js' {
  declare module.exports: $Exports<'brace/mode/jsx'>;
}
declare module 'brace/mode/julia.js' {
  declare module.exports: $Exports<'brace/mode/julia'>;
}
declare module 'brace/mode/kotlin.js' {
  declare module.exports: $Exports<'brace/mode/kotlin'>;
}
declare module 'brace/mode/latex.js' {
  declare module.exports: $Exports<'brace/mode/latex'>;
}
declare module 'brace/mode/lean.js' {
  declare module.exports: $Exports<'brace/mode/lean'>;
}
declare module 'brace/mode/less.js' {
  declare module.exports: $Exports<'brace/mode/less'>;
}
declare module 'brace/mode/liquid.js' {
  declare module.exports: $Exports<'brace/mode/liquid'>;
}
declare module 'brace/mode/lisp.js' {
  declare module.exports: $Exports<'brace/mode/lisp'>;
}
declare module 'brace/mode/live_script.js' {
  declare module.exports: $Exports<'brace/mode/live_script'>;
}
declare module 'brace/mode/livescript.js' {
  declare module.exports: $Exports<'brace/mode/livescript'>;
}
declare module 'brace/mode/logiql.js' {
  declare module.exports: $Exports<'brace/mode/logiql'>;
}
declare module 'brace/mode/lsl.js' {
  declare module.exports: $Exports<'brace/mode/lsl'>;
}
declare module 'brace/mode/lua.js' {
  declare module.exports: $Exports<'brace/mode/lua'>;
}
declare module 'brace/mode/luapage.js' {
  declare module.exports: $Exports<'brace/mode/luapage'>;
}
declare module 'brace/mode/lucene.js' {
  declare module.exports: $Exports<'brace/mode/lucene'>;
}
declare module 'brace/mode/makefile.js' {
  declare module.exports: $Exports<'brace/mode/makefile'>;
}
declare module 'brace/mode/markdown.js' {
  declare module.exports: $Exports<'brace/mode/markdown'>;
}
declare module 'brace/mode/mask.js' {
  declare module.exports: $Exports<'brace/mode/mask'>;
}
declare module 'brace/mode/matlab.js' {
  declare module.exports: $Exports<'brace/mode/matlab'>;
}
declare module 'brace/mode/mavens_mate_log.js' {
  declare module.exports: $Exports<'brace/mode/mavens_mate_log'>;
}
declare module 'brace/mode/maze.js' {
  declare module.exports: $Exports<'brace/mode/maze'>;
}
declare module 'brace/mode/mel.js' {
  declare module.exports: $Exports<'brace/mode/mel'>;
}
declare module 'brace/mode/mips_assembler.js' {
  declare module.exports: $Exports<'brace/mode/mips_assembler'>;
}
declare module 'brace/mode/mipsassembler.js' {
  declare module.exports: $Exports<'brace/mode/mipsassembler'>;
}
declare module 'brace/mode/mushcode.js' {
  declare module.exports: $Exports<'brace/mode/mushcode'>;
}
declare module 'brace/mode/mysql.js' {
  declare module.exports: $Exports<'brace/mode/mysql'>;
}
declare module 'brace/mode/nix.js' {
  declare module.exports: $Exports<'brace/mode/nix'>;
}
declare module 'brace/mode/nsis.js' {
  declare module.exports: $Exports<'brace/mode/nsis'>;
}
declare module 'brace/mode/objectivec.js' {
  declare module.exports: $Exports<'brace/mode/objectivec'>;
}
declare module 'brace/mode/ocaml.js' {
  declare module.exports: $Exports<'brace/mode/ocaml'>;
}
declare module 'brace/mode/pascal.js' {
  declare module.exports: $Exports<'brace/mode/pascal'>;
}
declare module 'brace/mode/perl.js' {
  declare module.exports: $Exports<'brace/mode/perl'>;
}
declare module 'brace/mode/pgsql.js' {
  declare module.exports: $Exports<'brace/mode/pgsql'>;
}
declare module 'brace/mode/php.js' {
  declare module.exports: $Exports<'brace/mode/php'>;
}
declare module 'brace/mode/pig.js' {
  declare module.exports: $Exports<'brace/mode/pig'>;
}
declare module 'brace/mode/plain_text.js' {
  declare module.exports: $Exports<'brace/mode/plain_text'>;
}
declare module 'brace/mode/powershell.js' {
  declare module.exports: $Exports<'brace/mode/powershell'>;
}
declare module 'brace/mode/praat.js' {
  declare module.exports: $Exports<'brace/mode/praat'>;
}
declare module 'brace/mode/prolog.js' {
  declare module.exports: $Exports<'brace/mode/prolog'>;
}
declare module 'brace/mode/properties.js' {
  declare module.exports: $Exports<'brace/mode/properties'>;
}
declare module 'brace/mode/protobuf.js' {
  declare module.exports: $Exports<'brace/mode/protobuf'>;
}
declare module 'brace/mode/python.js' {
  declare module.exports: $Exports<'brace/mode/python'>;
}
declare module 'brace/mode/r.js' {
  declare module.exports: $Exports<'brace/mode/r'>;
}
declare module 'brace/mode/razor.js' {
  declare module.exports: $Exports<'brace/mode/razor'>;
}
declare module 'brace/mode/rdoc.js' {
  declare module.exports: $Exports<'brace/mode/rdoc'>;
}
declare module 'brace/mode/red.js' {
  declare module.exports: $Exports<'brace/mode/red'>;
}
declare module 'brace/mode/rhtml.js' {
  declare module.exports: $Exports<'brace/mode/rhtml'>;
}
declare module 'brace/mode/rst.js' {
  declare module.exports: $Exports<'brace/mode/rst'>;
}
declare module 'brace/mode/ruby.js' {
  declare module.exports: $Exports<'brace/mode/ruby'>;
}
declare module 'brace/mode/rust.js' {
  declare module.exports: $Exports<'brace/mode/rust'>;
}
declare module 'brace/mode/sass.js' {
  declare module.exports: $Exports<'brace/mode/sass'>;
}
declare module 'brace/mode/scad.js' {
  declare module.exports: $Exports<'brace/mode/scad'>;
}
declare module 'brace/mode/scala.js' {
  declare module.exports: $Exports<'brace/mode/scala'>;
}
declare module 'brace/mode/scheme.js' {
  declare module.exports: $Exports<'brace/mode/scheme'>;
}
declare module 'brace/mode/scss.js' {
  declare module.exports: $Exports<'brace/mode/scss'>;
}
declare module 'brace/mode/sh.js' {
  declare module.exports: $Exports<'brace/mode/sh'>;
}
declare module 'brace/mode/sjs.js' {
  declare module.exports: $Exports<'brace/mode/sjs'>;
}
declare module 'brace/mode/smarty.js' {
  declare module.exports: $Exports<'brace/mode/smarty'>;
}
declare module 'brace/mode/snippets.js' {
  declare module.exports: $Exports<'brace/mode/snippets'>;
}
declare module 'brace/mode/soy_template.js' {
  declare module.exports: $Exports<'brace/mode/soy_template'>;
}
declare module 'brace/mode/space.js' {
  declare module.exports: $Exports<'brace/mode/space'>;
}
declare module 'brace/mode/sparql.js' {
  declare module.exports: $Exports<'brace/mode/sparql'>;
}
declare module 'brace/mode/sql.js' {
  declare module.exports: $Exports<'brace/mode/sql'>;
}
declare module 'brace/mode/sqlserver.js' {
  declare module.exports: $Exports<'brace/mode/sqlserver'>;
}
declare module 'brace/mode/stylus.js' {
  declare module.exports: $Exports<'brace/mode/stylus'>;
}
declare module 'brace/mode/svg.js' {
  declare module.exports: $Exports<'brace/mode/svg'>;
}
declare module 'brace/mode/swift.js' {
  declare module.exports: $Exports<'brace/mode/swift'>;
}
declare module 'brace/mode/swig.js' {
  declare module.exports: $Exports<'brace/mode/swig'>;
}
declare module 'brace/mode/tcl.js' {
  declare module.exports: $Exports<'brace/mode/tcl'>;
}
declare module 'brace/mode/tex.js' {
  declare module.exports: $Exports<'brace/mode/tex'>;
}
declare module 'brace/mode/text.js' {
  declare module.exports: $Exports<'brace/mode/text'>;
}
declare module 'brace/mode/textile.js' {
  declare module.exports: $Exports<'brace/mode/textile'>;
}
declare module 'brace/mode/toml.js' {
  declare module.exports: $Exports<'brace/mode/toml'>;
}
declare module 'brace/mode/tsx.js' {
  declare module.exports: $Exports<'brace/mode/tsx'>;
}
declare module 'brace/mode/turtle.js' {
  declare module.exports: $Exports<'brace/mode/turtle'>;
}
declare module 'brace/mode/twig.js' {
  declare module.exports: $Exports<'brace/mode/twig'>;
}
declare module 'brace/mode/typescript.js' {
  declare module.exports: $Exports<'brace/mode/typescript'>;
}
declare module 'brace/mode/vala.js' {
  declare module.exports: $Exports<'brace/mode/vala'>;
}
declare module 'brace/mode/vbscript.js' {
  declare module.exports: $Exports<'brace/mode/vbscript'>;
}
declare module 'brace/mode/velocity.js' {
  declare module.exports: $Exports<'brace/mode/velocity'>;
}
declare module 'brace/mode/verilog.js' {
  declare module.exports: $Exports<'brace/mode/verilog'>;
}
declare module 'brace/mode/vhdl.js' {
  declare module.exports: $Exports<'brace/mode/vhdl'>;
}
declare module 'brace/mode/wollok.js' {
  declare module.exports: $Exports<'brace/mode/wollok'>;
}
declare module 'brace/mode/xml.js' {
  declare module.exports: $Exports<'brace/mode/xml'>;
}
declare module 'brace/mode/xquery.js' {
  declare module.exports: $Exports<'brace/mode/xquery'>;
}
declare module 'brace/mode/yaml.js' {
  declare module.exports: $Exports<'brace/mode/yaml'>;
}
declare module 'brace/snippets/abap.js' {
  declare module.exports: $Exports<'brace/snippets/abap'>;
}
declare module 'brace/snippets/abc.js' {
  declare module.exports: $Exports<'brace/snippets/abc'>;
}
declare module 'brace/snippets/actionscript.js' {
  declare module.exports: $Exports<'brace/snippets/actionscript'>;
}
declare module 'brace/snippets/ada.js' {
  declare module.exports: $Exports<'brace/snippets/ada'>;
}
declare module 'brace/snippets/apache_conf.js' {
  declare module.exports: $Exports<'brace/snippets/apache_conf'>;
}
declare module 'brace/snippets/applescript.js' {
  declare module.exports: $Exports<'brace/snippets/applescript'>;
}
declare module 'brace/snippets/asciidoc.js' {
  declare module.exports: $Exports<'brace/snippets/asciidoc'>;
}
declare module 'brace/snippets/assembly_x86.js' {
  declare module.exports: $Exports<'brace/snippets/assembly_x86'>;
}
declare module 'brace/snippets/autohotkey.js' {
  declare module.exports: $Exports<'brace/snippets/autohotkey'>;
}
declare module 'brace/snippets/batchfile.js' {
  declare module.exports: $Exports<'brace/snippets/batchfile'>;
}
declare module 'brace/snippets/bro.js' {
  declare module.exports: $Exports<'brace/snippets/bro'>;
}
declare module 'brace/snippets/c_cpp.js' {
  declare module.exports: $Exports<'brace/snippets/c_cpp'>;
}
declare module 'brace/snippets/c9search.js' {
  declare module.exports: $Exports<'brace/snippets/c9search'>;
}
declare module 'brace/snippets/cirru.js' {
  declare module.exports: $Exports<'brace/snippets/cirru'>;
}
declare module 'brace/snippets/clojure.js' {
  declare module.exports: $Exports<'brace/snippets/clojure'>;
}
declare module 'brace/snippets/cobol.js' {
  declare module.exports: $Exports<'brace/snippets/cobol'>;
}
declare module 'brace/snippets/coffee.js' {
  declare module.exports: $Exports<'brace/snippets/coffee'>;
}
declare module 'brace/snippets/coldfusion.js' {
  declare module.exports: $Exports<'brace/snippets/coldfusion'>;
}
declare module 'brace/snippets/csharp.js' {
  declare module.exports: $Exports<'brace/snippets/csharp'>;
}
declare module 'brace/snippets/csound_document.js' {
  declare module.exports: $Exports<'brace/snippets/csound_document'>;
}
declare module 'brace/snippets/csound_orchestra.js' {
  declare module.exports: $Exports<'brace/snippets/csound_orchestra'>;
}
declare module 'brace/snippets/csound_score.js' {
  declare module.exports: $Exports<'brace/snippets/csound_score'>;
}
declare module 'brace/snippets/css.js' {
  declare module.exports: $Exports<'brace/snippets/css'>;
}
declare module 'brace/snippets/curly.js' {
  declare module.exports: $Exports<'brace/snippets/curly'>;
}
declare module 'brace/snippets/d.js' {
  declare module.exports: $Exports<'brace/snippets/d'>;
}
declare module 'brace/snippets/dart.js' {
  declare module.exports: $Exports<'brace/snippets/dart'>;
}
declare module 'brace/snippets/diff.js' {
  declare module.exports: $Exports<'brace/snippets/diff'>;
}
declare module 'brace/snippets/django.js' {
  declare module.exports: $Exports<'brace/snippets/django'>;
}
declare module 'brace/snippets/dockerfile.js' {
  declare module.exports: $Exports<'brace/snippets/dockerfile'>;
}
declare module 'brace/snippets/dot.js' {
  declare module.exports: $Exports<'brace/snippets/dot'>;
}
declare module 'brace/snippets/drools.js' {
  declare module.exports: $Exports<'brace/snippets/drools'>;
}
declare module 'brace/snippets/eiffel.js' {
  declare module.exports: $Exports<'brace/snippets/eiffel'>;
}
declare module 'brace/snippets/ejs.js' {
  declare module.exports: $Exports<'brace/snippets/ejs'>;
}
declare module 'brace/snippets/elixir.js' {
  declare module.exports: $Exports<'brace/snippets/elixir'>;
}
declare module 'brace/snippets/elm.js' {
  declare module.exports: $Exports<'brace/snippets/elm'>;
}
declare module 'brace/snippets/erlang.js' {
  declare module.exports: $Exports<'brace/snippets/erlang'>;
}
declare module 'brace/snippets/forth.js' {
  declare module.exports: $Exports<'brace/snippets/forth'>;
}
declare module 'brace/snippets/fortran.js' {
  declare module.exports: $Exports<'brace/snippets/fortran'>;
}
declare module 'brace/snippets/ftl.js' {
  declare module.exports: $Exports<'brace/snippets/ftl'>;
}
declare module 'brace/snippets/gcode.js' {
  declare module.exports: $Exports<'brace/snippets/gcode'>;
}
declare module 'brace/snippets/gherkin.js' {
  declare module.exports: $Exports<'brace/snippets/gherkin'>;
}
declare module 'brace/snippets/gitignore.js' {
  declare module.exports: $Exports<'brace/snippets/gitignore'>;
}
declare module 'brace/snippets/glsl.js' {
  declare module.exports: $Exports<'brace/snippets/glsl'>;
}
declare module 'brace/snippets/gobstones.js' {
  declare module.exports: $Exports<'brace/snippets/gobstones'>;
}
declare module 'brace/snippets/golang.js' {
  declare module.exports: $Exports<'brace/snippets/golang'>;
}
declare module 'brace/snippets/graphqlschema.js' {
  declare module.exports: $Exports<'brace/snippets/graphqlschema'>;
}
declare module 'brace/snippets/groovy.js' {
  declare module.exports: $Exports<'brace/snippets/groovy'>;
}
declare module 'brace/snippets/haml.js' {
  declare module.exports: $Exports<'brace/snippets/haml'>;
}
declare module 'brace/snippets/handlebars.js' {
  declare module.exports: $Exports<'brace/snippets/handlebars'>;
}
declare module 'brace/snippets/haskell_cabal.js' {
  declare module.exports: $Exports<'brace/snippets/haskell_cabal'>;
}
declare module 'brace/snippets/haskell.js' {
  declare module.exports: $Exports<'brace/snippets/haskell'>;
}
declare module 'brace/snippets/haxe.js' {
  declare module.exports: $Exports<'brace/snippets/haxe'>;
}
declare module 'brace/snippets/hjson.js' {
  declare module.exports: $Exports<'brace/snippets/hjson'>;
}
declare module 'brace/snippets/html_elixir.js' {
  declare module.exports: $Exports<'brace/snippets/html_elixir'>;
}
declare module 'brace/snippets/html_ruby.js' {
  declare module.exports: $Exports<'brace/snippets/html_ruby'>;
}
declare module 'brace/snippets/html.js' {
  declare module.exports: $Exports<'brace/snippets/html'>;
}
declare module 'brace/snippets/ini.js' {
  declare module.exports: $Exports<'brace/snippets/ini'>;
}
declare module 'brace/snippets/io.js' {
  declare module.exports: $Exports<'brace/snippets/io'>;
}
declare module 'brace/snippets/jack.js' {
  declare module.exports: $Exports<'brace/snippets/jack'>;
}
declare module 'brace/snippets/jade.js' {
  declare module.exports: $Exports<'brace/snippets/jade'>;
}
declare module 'brace/snippets/java.js' {
  declare module.exports: $Exports<'brace/snippets/java'>;
}
declare module 'brace/snippets/javascript.js' {
  declare module.exports: $Exports<'brace/snippets/javascript'>;
}
declare module 'brace/snippets/json.js' {
  declare module.exports: $Exports<'brace/snippets/json'>;
}
declare module 'brace/snippets/jsoniq.js' {
  declare module.exports: $Exports<'brace/snippets/jsoniq'>;
}
declare module 'brace/snippets/jsp.js' {
  declare module.exports: $Exports<'brace/snippets/jsp'>;
}
declare module 'brace/snippets/jssm.js' {
  declare module.exports: $Exports<'brace/snippets/jssm'>;
}
declare module 'brace/snippets/jsx.js' {
  declare module.exports: $Exports<'brace/snippets/jsx'>;
}
declare module 'brace/snippets/julia.js' {
  declare module.exports: $Exports<'brace/snippets/julia'>;
}
declare module 'brace/snippets/kotlin.js' {
  declare module.exports: $Exports<'brace/snippets/kotlin'>;
}
declare module 'brace/snippets/latex.js' {
  declare module.exports: $Exports<'brace/snippets/latex'>;
}
declare module 'brace/snippets/lean.js' {
  declare module.exports: $Exports<'brace/snippets/lean'>;
}
declare module 'brace/snippets/less.js' {
  declare module.exports: $Exports<'brace/snippets/less'>;
}
declare module 'brace/snippets/liquid.js' {
  declare module.exports: $Exports<'brace/snippets/liquid'>;
}
declare module 'brace/snippets/lisp.js' {
  declare module.exports: $Exports<'brace/snippets/lisp'>;
}
declare module 'brace/snippets/live_script.js' {
  declare module.exports: $Exports<'brace/snippets/live_script'>;
}
declare module 'brace/snippets/livescript.js' {
  declare module.exports: $Exports<'brace/snippets/livescript'>;
}
declare module 'brace/snippets/logiql.js' {
  declare module.exports: $Exports<'brace/snippets/logiql'>;
}
declare module 'brace/snippets/lsl.js' {
  declare module.exports: $Exports<'brace/snippets/lsl'>;
}
declare module 'brace/snippets/lua.js' {
  declare module.exports: $Exports<'brace/snippets/lua'>;
}
declare module 'brace/snippets/luapage.js' {
  declare module.exports: $Exports<'brace/snippets/luapage'>;
}
declare module 'brace/snippets/lucene.js' {
  declare module.exports: $Exports<'brace/snippets/lucene'>;
}
declare module 'brace/snippets/makefile.js' {
  declare module.exports: $Exports<'brace/snippets/makefile'>;
}
declare module 'brace/snippets/markdown.js' {
  declare module.exports: $Exports<'brace/snippets/markdown'>;
}
declare module 'brace/snippets/mask.js' {
  declare module.exports: $Exports<'brace/snippets/mask'>;
}
declare module 'brace/snippets/matlab.js' {
  declare module.exports: $Exports<'brace/snippets/matlab'>;
}
declare module 'brace/snippets/maze.js' {
  declare module.exports: $Exports<'brace/snippets/maze'>;
}
declare module 'brace/snippets/mel.js' {
  declare module.exports: $Exports<'brace/snippets/mel'>;
}
declare module 'brace/snippets/mips_assembler.js' {
  declare module.exports: $Exports<'brace/snippets/mips_assembler'>;
}
declare module 'brace/snippets/mipsassembler.js' {
  declare module.exports: $Exports<'brace/snippets/mipsassembler'>;
}
declare module 'brace/snippets/mushcode.js' {
  declare module.exports: $Exports<'brace/snippets/mushcode'>;
}
declare module 'brace/snippets/mysql.js' {
  declare module.exports: $Exports<'brace/snippets/mysql'>;
}
declare module 'brace/snippets/nix.js' {
  declare module.exports: $Exports<'brace/snippets/nix'>;
}
declare module 'brace/snippets/nsis.js' {
  declare module.exports: $Exports<'brace/snippets/nsis'>;
}
declare module 'brace/snippets/objectivec.js' {
  declare module.exports: $Exports<'brace/snippets/objectivec'>;
}
declare module 'brace/snippets/ocaml.js' {
  declare module.exports: $Exports<'brace/snippets/ocaml'>;
}
declare module 'brace/snippets/pascal.js' {
  declare module.exports: $Exports<'brace/snippets/pascal'>;
}
declare module 'brace/snippets/perl.js' {
  declare module.exports: $Exports<'brace/snippets/perl'>;
}
declare module 'brace/snippets/pgsql.js' {
  declare module.exports: $Exports<'brace/snippets/pgsql'>;
}
declare module 'brace/snippets/php.js' {
  declare module.exports: $Exports<'brace/snippets/php'>;
}
declare module 'brace/snippets/pig.js' {
  declare module.exports: $Exports<'brace/snippets/pig'>;
}
declare module 'brace/snippets/plain_text.js' {
  declare module.exports: $Exports<'brace/snippets/plain_text'>;
}
declare module 'brace/snippets/powershell.js' {
  declare module.exports: $Exports<'brace/snippets/powershell'>;
}
declare module 'brace/snippets/praat.js' {
  declare module.exports: $Exports<'brace/snippets/praat'>;
}
declare module 'brace/snippets/prolog.js' {
  declare module.exports: $Exports<'brace/snippets/prolog'>;
}
declare module 'brace/snippets/properties.js' {
  declare module.exports: $Exports<'brace/snippets/properties'>;
}
declare module 'brace/snippets/protobuf.js' {
  declare module.exports: $Exports<'brace/snippets/protobuf'>;
}
declare module 'brace/snippets/python.js' {
  declare module.exports: $Exports<'brace/snippets/python'>;
}
declare module 'brace/snippets/r.js' {
  declare module.exports: $Exports<'brace/snippets/r'>;
}
declare module 'brace/snippets/razor.js' {
  declare module.exports: $Exports<'brace/snippets/razor'>;
}
declare module 'brace/snippets/rdoc.js' {
  declare module.exports: $Exports<'brace/snippets/rdoc'>;
}
declare module 'brace/snippets/red.js' {
  declare module.exports: $Exports<'brace/snippets/red'>;
}
declare module 'brace/snippets/rhtml.js' {
  declare module.exports: $Exports<'brace/snippets/rhtml'>;
}
declare module 'brace/snippets/rst.js' {
  declare module.exports: $Exports<'brace/snippets/rst'>;
}
declare module 'brace/snippets/ruby.js' {
  declare module.exports: $Exports<'brace/snippets/ruby'>;
}
declare module 'brace/snippets/rust.js' {
  declare module.exports: $Exports<'brace/snippets/rust'>;
}
declare module 'brace/snippets/sass.js' {
  declare module.exports: $Exports<'brace/snippets/sass'>;
}
declare module 'brace/snippets/scad.js' {
  declare module.exports: $Exports<'brace/snippets/scad'>;
}
declare module 'brace/snippets/scala.js' {
  declare module.exports: $Exports<'brace/snippets/scala'>;
}
declare module 'brace/snippets/scheme.js' {
  declare module.exports: $Exports<'brace/snippets/scheme'>;
}
declare module 'brace/snippets/scss.js' {
  declare module.exports: $Exports<'brace/snippets/scss'>;
}
declare module 'brace/snippets/sh.js' {
  declare module.exports: $Exports<'brace/snippets/sh'>;
}
declare module 'brace/snippets/sjs.js' {
  declare module.exports: $Exports<'brace/snippets/sjs'>;
}
declare module 'brace/snippets/smarty.js' {
  declare module.exports: $Exports<'brace/snippets/smarty'>;
}
declare module 'brace/snippets/snippets.js' {
  declare module.exports: $Exports<'brace/snippets/snippets'>;
}
declare module 'brace/snippets/soy_template.js' {
  declare module.exports: $Exports<'brace/snippets/soy_template'>;
}
declare module 'brace/snippets/space.js' {
  declare module.exports: $Exports<'brace/snippets/space'>;
}
declare module 'brace/snippets/sparql.js' {
  declare module.exports: $Exports<'brace/snippets/sparql'>;
}
declare module 'brace/snippets/sql.js' {
  declare module.exports: $Exports<'brace/snippets/sql'>;
}
declare module 'brace/snippets/sqlserver.js' {
  declare module.exports: $Exports<'brace/snippets/sqlserver'>;
}
declare module 'brace/snippets/stylus.js' {
  declare module.exports: $Exports<'brace/snippets/stylus'>;
}
declare module 'brace/snippets/svg.js' {
  declare module.exports: $Exports<'brace/snippets/svg'>;
}
declare module 'brace/snippets/swift.js' {
  declare module.exports: $Exports<'brace/snippets/swift'>;
}
declare module 'brace/snippets/swig.js' {
  declare module.exports: $Exports<'brace/snippets/swig'>;
}
declare module 'brace/snippets/tcl.js' {
  declare module.exports: $Exports<'brace/snippets/tcl'>;
}
declare module 'brace/snippets/tex.js' {
  declare module.exports: $Exports<'brace/snippets/tex'>;
}
declare module 'brace/snippets/text.js' {
  declare module.exports: $Exports<'brace/snippets/text'>;
}
declare module 'brace/snippets/textile.js' {
  declare module.exports: $Exports<'brace/snippets/textile'>;
}
declare module 'brace/snippets/toml.js' {
  declare module.exports: $Exports<'brace/snippets/toml'>;
}
declare module 'brace/snippets/tsx.js' {
  declare module.exports: $Exports<'brace/snippets/tsx'>;
}
declare module 'brace/snippets/turtle.js' {
  declare module.exports: $Exports<'brace/snippets/turtle'>;
}
declare module 'brace/snippets/twig.js' {
  declare module.exports: $Exports<'brace/snippets/twig'>;
}
declare module 'brace/snippets/typescript.js' {
  declare module.exports: $Exports<'brace/snippets/typescript'>;
}
declare module 'brace/snippets/vala.js' {
  declare module.exports: $Exports<'brace/snippets/vala'>;
}
declare module 'brace/snippets/vbscript.js' {
  declare module.exports: $Exports<'brace/snippets/vbscript'>;
}
declare module 'brace/snippets/velocity.js' {
  declare module.exports: $Exports<'brace/snippets/velocity'>;
}
declare module 'brace/snippets/verilog.js' {
  declare module.exports: $Exports<'brace/snippets/verilog'>;
}
declare module 'brace/snippets/vhdl.js' {
  declare module.exports: $Exports<'brace/snippets/vhdl'>;
}
declare module 'brace/snippets/wollok.js' {
  declare module.exports: $Exports<'brace/snippets/wollok'>;
}
declare module 'brace/snippets/xml.js' {
  declare module.exports: $Exports<'brace/snippets/xml'>;
}
declare module 'brace/snippets/xquery.js' {
  declare module.exports: $Exports<'brace/snippets/xquery'>;
}
declare module 'brace/snippets/yaml.js' {
  declare module.exports: $Exports<'brace/snippets/yaml'>;
}
declare module 'brace/test/error-annotations.js' {
  declare module.exports: $Exports<'brace/test/error-annotations'>;
}
declare module 'brace/test/fixtures/coffee-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/coffee-editor'>;
}
declare module 'brace/test/fixtures/javascript-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/javascript-editor'>;
}
declare module 'brace/test/fixtures/json-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/json-editor'>;
}
declare module 'brace/test/fixtures/lua-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/lua-editor'>;
}
declare module 'brace/test/fixtures/xml-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/xml-editor'>;
}
declare module 'brace/test/stringified/style.js' {
  declare module.exports: $Exports<'brace/test/stringified/style'>;
}
declare module 'brace/theme/ambiance.js' {
  declare module.exports: $Exports<'brace/theme/ambiance'>;
}
declare module 'brace/theme/chaos.js' {
  declare module.exports: $Exports<'brace/theme/chaos'>;
}
declare module 'brace/theme/chrome.js' {
  declare module.exports: $Exports<'brace/theme/chrome'>;
}
declare module 'brace/theme/clouds_midnight.js' {
  declare module.exports: $Exports<'brace/theme/clouds_midnight'>;
}
declare module 'brace/theme/clouds.js' {
  declare module.exports: $Exports<'brace/theme/clouds'>;
}
declare module 'brace/theme/cobalt.js' {
  declare module.exports: $Exports<'brace/theme/cobalt'>;
}
declare module 'brace/theme/crimson_editor.js' {
  declare module.exports: $Exports<'brace/theme/crimson_editor'>;
}
declare module 'brace/theme/dawn.js' {
  declare module.exports: $Exports<'brace/theme/dawn'>;
}
declare module 'brace/theme/dracula.js' {
  declare module.exports: $Exports<'brace/theme/dracula'>;
}
declare module 'brace/theme/dreamweaver.js' {
  declare module.exports: $Exports<'brace/theme/dreamweaver'>;
}
declare module 'brace/theme/eclipse.js' {
  declare module.exports: $Exports<'brace/theme/eclipse'>;
}
declare module 'brace/theme/github.js' {
  declare module.exports: $Exports<'brace/theme/github'>;
}
declare module 'brace/theme/gob.js' {
  declare module.exports: $Exports<'brace/theme/gob'>;
}
declare module 'brace/theme/gruvbox.js' {
  declare module.exports: $Exports<'brace/theme/gruvbox'>;
}
declare module 'brace/theme/idle_fingers.js' {
  declare module.exports: $Exports<'brace/theme/idle_fingers'>;
}
declare module 'brace/theme/iplastic.js' {
  declare module.exports: $Exports<'brace/theme/iplastic'>;
}
declare module 'brace/theme/katzenmilch.js' {
  declare module.exports: $Exports<'brace/theme/katzenmilch'>;
}
declare module 'brace/theme/kr_theme.js' {
  declare module.exports: $Exports<'brace/theme/kr_theme'>;
}
declare module 'brace/theme/kuroir.js' {
  declare module.exports: $Exports<'brace/theme/kuroir'>;
}
declare module 'brace/theme/merbivore_soft.js' {
  declare module.exports: $Exports<'brace/theme/merbivore_soft'>;
}
declare module 'brace/theme/merbivore.js' {
  declare module.exports: $Exports<'brace/theme/merbivore'>;
}
declare module 'brace/theme/mono_industrial.js' {
  declare module.exports: $Exports<'brace/theme/mono_industrial'>;
}
declare module 'brace/theme/monokai.js' {
  declare module.exports: $Exports<'brace/theme/monokai'>;
}
declare module 'brace/theme/pastel_on_dark.js' {
  declare module.exports: $Exports<'brace/theme/pastel_on_dark'>;
}
declare module 'brace/theme/solarized_dark.js' {
  declare module.exports: $Exports<'brace/theme/solarized_dark'>;
}
declare module 'brace/theme/solarized_light.js' {
  declare module.exports: $Exports<'brace/theme/solarized_light'>;
}
declare module 'brace/theme/sqlserver.js' {
  declare module.exports: $Exports<'brace/theme/sqlserver'>;
}
declare module 'brace/theme/terminal.js' {
  declare module.exports: $Exports<'brace/theme/terminal'>;
}
declare module 'brace/theme/textmate.js' {
  declare module.exports: $Exports<'brace/theme/textmate'>;
}
declare module 'brace/theme/tomorrow_night_blue.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night_blue'>;
}
declare module 'brace/theme/tomorrow_night_bright.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night_bright'>;
}
declare module 'brace/theme/tomorrow_night_eighties.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night_eighties'>;
}
declare module 'brace/theme/tomorrow_night.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night'>;
}
declare module 'brace/theme/tomorrow.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow'>;
}
declare module 'brace/theme/twilight.js' {
  declare module.exports: $Exports<'brace/theme/twilight'>;
}
declare module 'brace/theme/vibrant_ink.js' {
  declare module.exports: $Exports<'brace/theme/vibrant_ink'>;
}
declare module 'brace/theme/xcode.js' {
  declare module.exports: $Exports<'brace/theme/xcode'>;
}
declare module 'brace/worker/coffee.js' {
  declare module.exports: $Exports<'brace/worker/coffee'>;
}
declare module 'brace/worker/css.js' {
  declare module.exports: $Exports<'brace/worker/css'>;
}
declare module 'brace/worker/html.js' {
  declare module.exports: $Exports<'brace/worker/html'>;
}
declare module 'brace/worker/javascript.js' {
  declare module.exports: $Exports<'brace/worker/javascript'>;
}
declare module 'brace/worker/json.js' {
  declare module.exports: $Exports<'brace/worker/json'>;
}
declare module 'brace/worker/lua.js' {
  declare module.exports: $Exports<'brace/worker/lua'>;
}
declare module 'brace/worker/xml.js' {
  declare module.exports: $Exports<'brace/worker/xml'>;
}
