// flow-typed signature: c9d1906dd773a8312849a0c919c90daf
// flow-typed version: <<STUB>>/hotel_v^0.8.7/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hotel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hotel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hotel/bin/uninstall' {
  declare module.exports: any;
}

declare module 'hotel/dist/bundle' {
  declare module.exports: any;
}

declare module 'hotel/lib/cli/bin' {
  declare module.exports: any;
}

declare module 'hotel/lib/cli/daemon' {
  declare module.exports: any;
}

declare module 'hotel/lib/cli/index' {
  declare module.exports: any;
}

declare module 'hotel/lib/cli/run' {
  declare module.exports: any;
}

declare module 'hotel/lib/cli/servers' {
  declare module.exports: any;
}

declare module 'hotel/lib/common' {
  declare module.exports: any;
}

declare module 'hotel/lib/conf' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/app' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/group' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/index' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/loader' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/log' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/pem' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/routers/api/events' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/routers/api/index' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/routers/api/servers' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/routers/index' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/tcp-proxy' {
  declare module.exports: any;
}

declare module 'hotel/lib/daemon/vhosts/tld' {
  declare module.exports: any;
}

declare module 'hotel/lib/get-cmd' {
  declare module.exports: any;
}

declare module 'hotel/lib/pid-file' {
  declare module.exports: any;
}

declare module 'hotel/lib/scripts/uninstall' {
  declare module.exports: any;
}

declare module 'hotel/test/_setup' {
  declare module.exports: any;
}

declare module 'hotel/test/cli/daemon' {
  declare module.exports: any;
}

declare module 'hotel/test/cli/run' {
  declare module.exports: any;
}

declare module 'hotel/test/cli/servers' {
  declare module.exports: any;
}

declare module 'hotel/test/daemon/app' {
  declare module.exports: any;
}

declare module 'hotel/test/daemon/group' {
  declare module.exports: any;
}

declare module 'hotel/test/daemon/pem' {
  declare module.exports: any;
}

declare module 'hotel/test/fixtures/app/index' {
  declare module.exports: any;
}

declare module 'hotel/test/fixtures/verbose/index' {
  declare module.exports: any;
}

declare module 'hotel/webpack.common' {
  declare module.exports: any;
}

declare module 'hotel/webpack.dev' {
  declare module.exports: any;
}

declare module 'hotel/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hotel/bin/uninstall.js' {
  declare module.exports: $Exports<'hotel/bin/uninstall'>;
}
declare module 'hotel/dist/bundle.js' {
  declare module.exports: $Exports<'hotel/dist/bundle'>;
}
declare module 'hotel/lib/cli/bin.js' {
  declare module.exports: $Exports<'hotel/lib/cli/bin'>;
}
declare module 'hotel/lib/cli/daemon.js' {
  declare module.exports: $Exports<'hotel/lib/cli/daemon'>;
}
declare module 'hotel/lib/cli/index.js' {
  declare module.exports: $Exports<'hotel/lib/cli/index'>;
}
declare module 'hotel/lib/cli/run.js' {
  declare module.exports: $Exports<'hotel/lib/cli/run'>;
}
declare module 'hotel/lib/cli/servers.js' {
  declare module.exports: $Exports<'hotel/lib/cli/servers'>;
}
declare module 'hotel/lib/common.js' {
  declare module.exports: $Exports<'hotel/lib/common'>;
}
declare module 'hotel/lib/conf.js' {
  declare module.exports: $Exports<'hotel/lib/conf'>;
}
declare module 'hotel/lib/daemon/app.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/app'>;
}
declare module 'hotel/lib/daemon/group.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/group'>;
}
declare module 'hotel/lib/daemon/index.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/index'>;
}
declare module 'hotel/lib/daemon/loader.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/loader'>;
}
declare module 'hotel/lib/daemon/log.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/log'>;
}
declare module 'hotel/lib/daemon/pem.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/pem'>;
}
declare module 'hotel/lib/daemon/routers/api/events.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/routers/api/events'>;
}
declare module 'hotel/lib/daemon/routers/api/index.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/routers/api/index'>;
}
declare module 'hotel/lib/daemon/routers/api/servers.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/routers/api/servers'>;
}
declare module 'hotel/lib/daemon/routers/index.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/routers/index'>;
}
declare module 'hotel/lib/daemon/tcp-proxy.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/tcp-proxy'>;
}
declare module 'hotel/lib/daemon/vhosts/tld.js' {
  declare module.exports: $Exports<'hotel/lib/daemon/vhosts/tld'>;
}
declare module 'hotel/lib/get-cmd.js' {
  declare module.exports: $Exports<'hotel/lib/get-cmd'>;
}
declare module 'hotel/lib/pid-file.js' {
  declare module.exports: $Exports<'hotel/lib/pid-file'>;
}
declare module 'hotel/lib/scripts/uninstall.js' {
  declare module.exports: $Exports<'hotel/lib/scripts/uninstall'>;
}
declare module 'hotel/test/_setup.js' {
  declare module.exports: $Exports<'hotel/test/_setup'>;
}
declare module 'hotel/test/cli/daemon.js' {
  declare module.exports: $Exports<'hotel/test/cli/daemon'>;
}
declare module 'hotel/test/cli/run.js' {
  declare module.exports: $Exports<'hotel/test/cli/run'>;
}
declare module 'hotel/test/cli/servers.js' {
  declare module.exports: $Exports<'hotel/test/cli/servers'>;
}
declare module 'hotel/test/daemon/app.js' {
  declare module.exports: $Exports<'hotel/test/daemon/app'>;
}
declare module 'hotel/test/daemon/group.js' {
  declare module.exports: $Exports<'hotel/test/daemon/group'>;
}
declare module 'hotel/test/daemon/pem.js' {
  declare module.exports: $Exports<'hotel/test/daemon/pem'>;
}
declare module 'hotel/test/fixtures/app/index.js' {
  declare module.exports: $Exports<'hotel/test/fixtures/app/index'>;
}
declare module 'hotel/test/fixtures/verbose/index.js' {
  declare module.exports: $Exports<'hotel/test/fixtures/verbose/index'>;
}
declare module 'hotel/webpack.common.js' {
  declare module.exports: $Exports<'hotel/webpack.common'>;
}
declare module 'hotel/webpack.dev.js' {
  declare module.exports: $Exports<'hotel/webpack.dev'>;
}
declare module 'hotel/webpack.prod.js' {
  declare module.exports: $Exports<'hotel/webpack.prod'>;
}
