// flow-typed signature: 738ae4cfd08087d6c9b1dbc9a79b8cfa
// flow-typed version: <<STUB>>/json-to-ast_v^2.0.5/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-to-ast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-to-ast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-to-ast/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-to-ast/build.js' {
  declare module.exports: $Exports<'json-to-ast/build'>;
}
