// flow-typed signature: 8e7a12cc07bed52a315432644aeff3e9
// flow-typed version: <<STUB>>/json5_v^1.0.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json5/dist/index' {
  declare module.exports: any;
}

declare module 'json5/lib/cli' {
  declare module.exports: any;
}

declare module 'json5/lib/index' {
  declare module.exports: any;
}

declare module 'json5/lib/parse' {
  declare module.exports: any;
}

declare module 'json5/lib/register' {
  declare module.exports: any;
}

declare module 'json5/lib/require' {
  declare module.exports: any;
}

declare module 'json5/lib/stringify' {
  declare module.exports: any;
}

declare module 'json5/lib/unicode' {
  declare module.exports: any;
}

declare module 'json5/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json5/dist/index.js' {
  declare module.exports: $Exports<'json5/dist/index'>;
}
declare module 'json5/lib/cli.js' {
  declare module.exports: $Exports<'json5/lib/cli'>;
}
declare module 'json5/lib/index.js' {
  declare module.exports: $Exports<'json5/lib/index'>;
}
declare module 'json5/lib/parse.js' {
  declare module.exports: $Exports<'json5/lib/parse'>;
}
declare module 'json5/lib/register.js' {
  declare module.exports: $Exports<'json5/lib/register'>;
}
declare module 'json5/lib/require.js' {
  declare module.exports: $Exports<'json5/lib/require'>;
}
declare module 'json5/lib/stringify.js' {
  declare module.exports: $Exports<'json5/lib/stringify'>;
}
declare module 'json5/lib/unicode.js' {
  declare module.exports: $Exports<'json5/lib/unicode'>;
}
declare module 'json5/lib/util.js' {
  declare module.exports: $Exports<'json5/lib/util'>;
}
