// flow-typed signature: aa0612f676da3283ffa0de508b262aa8
// flow-typed version: <<STUB>>/koa-send_v^5.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-send'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-send' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-send/index' {
  declare module.exports: $Exports<'koa-send'>;
}
declare module 'koa-send/index.js' {
  declare module.exports: $Exports<'koa-send'>;
}
