// flow-typed signature: b761079ed1956a965c5852a480b01d85
// flow-typed version: <<STUB>>/monaco-vim_v^0.0.7/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monaco-vim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monaco-vim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monaco-vim/dist/monaco-vim' {
  declare module.exports: any;
}

declare module 'monaco-vim/lib/cm_adapter' {
  declare module.exports: any;
}

declare module 'monaco-vim/lib/cm/keymap_vim' {
  declare module.exports: any;
}

declare module 'monaco-vim/lib/index' {
  declare module.exports: any;
}

declare module 'monaco-vim/lib/statusbar' {
  declare module.exports: any;
}

declare module 'monaco-vim/src/cm_adapter' {
  declare module.exports: any;
}

declare module 'monaco-vim/src/cm/keymap_vim' {
  declare module.exports: any;
}

declare module 'monaco-vim/src/demo' {
  declare module.exports: any;
}

declare module 'monaco-vim/src/index' {
  declare module.exports: any;
}

declare module 'monaco-vim/src/statusbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monaco-vim/dist/monaco-vim.js' {
  declare module.exports: $Exports<'monaco-vim/dist/monaco-vim'>;
}
declare module 'monaco-vim/lib/cm_adapter.js' {
  declare module.exports: $Exports<'monaco-vim/lib/cm_adapter'>;
}
declare module 'monaco-vim/lib/cm/keymap_vim.js' {
  declare module.exports: $Exports<'monaco-vim/lib/cm/keymap_vim'>;
}
declare module 'monaco-vim/lib/index.js' {
  declare module.exports: $Exports<'monaco-vim/lib/index'>;
}
declare module 'monaco-vim/lib/statusbar.js' {
  declare module.exports: $Exports<'monaco-vim/lib/statusbar'>;
}
declare module 'monaco-vim/src/cm_adapter.js' {
  declare module.exports: $Exports<'monaco-vim/src/cm_adapter'>;
}
declare module 'monaco-vim/src/cm/keymap_vim.js' {
  declare module.exports: $Exports<'monaco-vim/src/cm/keymap_vim'>;
}
declare module 'monaco-vim/src/demo.js' {
  declare module.exports: $Exports<'monaco-vim/src/demo'>;
}
declare module 'monaco-vim/src/index.js' {
  declare module.exports: $Exports<'monaco-vim/src/index'>;
}
declare module 'monaco-vim/src/statusbar.js' {
  declare module.exports: $Exports<'monaco-vim/src/statusbar'>;
}
