// flow-typed signature: 472840fd534181578514acdbb4b98117
// flow-typed version: <<STUB>>/react-textarea-autosize_v^7.0.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textarea-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-textarea-autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.browser' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.esm.browser' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.esm' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.browser.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.cjs.browser'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.cjs'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.esm.browser.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.esm.browser'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.esm.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.esm'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.min.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.min'>;
}
