// flow-typed signature: 77d2bb4dc1c0fad8ac4b8f7b59426984
// flow-typed version: <<STUB>>/react-loading-indicator_v^1.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading-indicator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loading-indicator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loading-indicator/build/LoadingIndicator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loading-indicator/build/LoadingIndicator.js' {
  declare module.exports: $Exports<'react-loading-indicator/build/LoadingIndicator'>;
}
