// flow-typed signature: 70ee27d7bfe0af799b9d6237cf5cb37c
// flow-typed version: <<STUB>>/stoppable_v^1.0.6/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stoppable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stoppable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stoppable/lib/stoppable' {
  declare module.exports: any;
}

declare module 'stoppable/test/performance' {
  declare module.exports: any;
}

declare module 'stoppable/test/server' {
  declare module.exports: any;
}

declare module 'stoppable/test/stoppable.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stoppable/lib/stoppable.js' {
  declare module.exports: $Exports<'stoppable/lib/stoppable'>;
}
declare module 'stoppable/test/performance.js' {
  declare module.exports: $Exports<'stoppable/test/performance'>;
}
declare module 'stoppable/test/server.js' {
  declare module.exports: $Exports<'stoppable/test/server'>;
}
declare module 'stoppable/test/stoppable.test.js' {
  declare module.exports: $Exports<'stoppable/test/stoppable.test'>;
}
