// flow-typed signature: 09ee20027d469e5b112008df74f5a0ce
// flow-typed version: <<STUB>>/uglifyjs-webpack-plugin_v^2.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyjs-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyjs-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglifyjs-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'uglifyjs-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'uglifyjs-webpack-plugin/dist/minify' {
  declare module.exports: any;
}

declare module 'uglifyjs-webpack-plugin/dist/TaskRunner' {
  declare module.exports: any;
}

declare module 'uglifyjs-webpack-plugin/dist/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglifyjs-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/dist/cjs'>;
}
declare module 'uglifyjs-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/dist/index'>;
}
declare module 'uglifyjs-webpack-plugin/dist/minify.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/dist/minify'>;
}
declare module 'uglifyjs-webpack-plugin/dist/TaskRunner.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/dist/TaskRunner'>;
}
declare module 'uglifyjs-webpack-plugin/dist/worker.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/dist/worker'>;
}
