// flow-typed signature: 199d56ac419fa82453df47de9c36910a
// flow-typed version: <<STUB>>/webpack-serve_v^2.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-serve/lib/app' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/bus' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/cli' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/compiler' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/config' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/flags' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/global' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/middleware/ContentMiddleware' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/middleware/MiddlewareState' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/middleware/WebpackMiddleware' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/options' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/server' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/WebpackServeError' {
  declare module.exports: any;
}

declare module 'webpack-serve/schemas/flags' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-serve/lib/app.js' {
  declare module.exports: $Exports<'webpack-serve/lib/app'>;
}
declare module 'webpack-serve/lib/bus.js' {
  declare module.exports: $Exports<'webpack-serve/lib/bus'>;
}
declare module 'webpack-serve/lib/cli.js' {
  declare module.exports: $Exports<'webpack-serve/lib/cli'>;
}
declare module 'webpack-serve/lib/compiler.js' {
  declare module.exports: $Exports<'webpack-serve/lib/compiler'>;
}
declare module 'webpack-serve/lib/config.js' {
  declare module.exports: $Exports<'webpack-serve/lib/config'>;
}
declare module 'webpack-serve/lib/flags.js' {
  declare module.exports: $Exports<'webpack-serve/lib/flags'>;
}
declare module 'webpack-serve/lib/global.js' {
  declare module.exports: $Exports<'webpack-serve/lib/global'>;
}
declare module 'webpack-serve/lib/index.js' {
  declare module.exports: $Exports<'webpack-serve/lib/index'>;
}
declare module 'webpack-serve/lib/middleware/ContentMiddleware.js' {
  declare module.exports: $Exports<'webpack-serve/lib/middleware/ContentMiddleware'>;
}
declare module 'webpack-serve/lib/middleware/MiddlewareState.js' {
  declare module.exports: $Exports<'webpack-serve/lib/middleware/MiddlewareState'>;
}
declare module 'webpack-serve/lib/middleware/WebpackMiddleware.js' {
  declare module.exports: $Exports<'webpack-serve/lib/middleware/WebpackMiddleware'>;
}
declare module 'webpack-serve/lib/options.js' {
  declare module.exports: $Exports<'webpack-serve/lib/options'>;
}
declare module 'webpack-serve/lib/server.js' {
  declare module.exports: $Exports<'webpack-serve/lib/server'>;
}
declare module 'webpack-serve/lib/WebpackServeError.js' {
  declare module.exports: $Exports<'webpack-serve/lib/WebpackServeError'>;
}
declare module 'webpack-serve/schemas/flags.js' {
  declare module.exports: $Exports<'webpack-serve/schemas/flags'>;
}
