// flow-typed signature: fcc9bfa54cb0d2f188b82176079a6915
// flow-typed version: <<STUB>>/worker-plugin_v^1.1.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'worker-plugin/dist/loader' {
  declare module.exports: any;
}

declare module 'worker-plugin/dist/worker-plugin' {
  declare module.exports: any;
}

declare module 'worker-plugin/src/index' {
  declare module.exports: any;
}

declare module 'worker-plugin/src/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'worker-plugin/dist/loader.js' {
  declare module.exports: $Exports<'worker-plugin/dist/loader'>;
}
declare module 'worker-plugin/dist/worker-plugin.js' {
  declare module.exports: $Exports<'worker-plugin/dist/worker-plugin'>;
}
declare module 'worker-plugin/src/index.js' {
  declare module.exports: $Exports<'worker-plugin/src/index'>;
}
declare module 'worker-plugin/src/loader.js' {
  declare module.exports: $Exports<'worker-plugin/src/loader'>;
}
