// flow-typed signature: 3ecbb73567b5392c96367e50e5d09455
// flow-typed version: <<STUB>>/@expo/spawn-async_v^1.3.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/spawn-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/spawn-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/spawn-async/build/spawnAsync' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/spawn-async/build/spawnAsync.js' {
  declare module.exports: $Exports<'@expo/spawn-async/build/spawnAsync'>;
}
