// flow-typed signature: cc49bd3144cb24d4302af0092f9b4ba0
// flow-typed version: <<STUB>>/@koa/cors_v^2.2.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@koa/cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@koa/cors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@koa/cors/index' {
  declare module.exports: $Exports<'@koa/cors'>;
}
declare module '@koa/cors/index.js' {
  declare module.exports: $Exports<'@koa/cors'>;
}
